### PR TITLE
grammer fixed

### PR DESCRIPTION
**Pull request by SaeedaRasuly**

### CODE REVIEW

**Comment by NaveedAhmadHematmal** [comment]
Sorry! Your branch doesn't meet our project standard and you should add your data to Advanced Grammar file instead of creating another one. 
Be patient and try it again.

**Comment by NaveedAhmadHematmal** [comment]
saeeda/add/moreexamples
saeeda/addition/verb/examples
are different standards for branch names, use add or addition. and use three folder or four folder names.

**Comment by SaeedaRasuly** [comment]
Now I added the grammer to advanced grammer file. check it and I made pull request

**Comment by SaeedaRasuly** [comment]
The grammer file were successfully fixed

**Comment by NaveedAhmadHematmal** [comment]
yeah! thank you, I accepted it.

**Pull request merged**
